import {execFileSync} from 'node:child_process';
import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
import {resolve,dirname,basename} from 'node:path';
const output=resolve('dist');
if(dirname(output)!==process.cwd()||basename(output)!=='dist')throw Error('Invalid build directory');
await rm(output,{recursive:true,force:true});
await mkdir(output,{recursive:true});
await cp('public',output,{recursive:true});
await cp('src',resolve(output,'src'),{recursive:true});
const revision=process.env.VERCEL_GIT_COMMIT_SHA||process.env.GITHUB_SHA||execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
await writeFile(resolve(output,'build-info.json'),JSON.stringify({revision}));
console.log('Mission 2050 built into dist.');
