import test from 'node:test';
import assert from 'node:assert/strict';
import {freshAdventure,actionsFor,act,restoreAdventure,phaseOf} from '../src/adventure.js';
const missions=[['fuse','power','circuit','clinic','gem'],['panels','panel1','panel2','panel3','gem'],['stakes','housing1','housing2','grove','water1','water2','gem'],['scan1','scan2','scan3','valve','gem'],['cargo','depotDelivery','clinicDelivery','budget:buses','budget:cycling','budget:backup','budget:training','night','gem']];
function install(a){a=act(a,'lift');a=act(a,'assemble');return act(a,'lift');}
function run(stop=5){let a=freshAdventure();for(let i=0;i<stop;i++){for(const id of missions[i])a=act(a,id);a=install(a);}return a;}
test('Five physical missions and assembled stones unlock final activation',()=>{const a=act(act(run(),'lift'),'activate');assert.equal(a.ending.ending,'green');assert.deepEqual(a.assembled,[0,1,2,3,4]);assert.equal(a.rules.stage,4);});
test('A collected stone must return to the reactor before next district',()=>{let a=freshAdventure();for(const id of missions[0])a=act(a,id);assert.equal(phaseOf(a),0);assert.deepEqual(actionsFor(a).map(x=>x.id),['lift']);assert.throws(()=>act(a,'assemble'));a=act(a,'lift');assert.throws(()=>act(a,'panels'));a=act(a,'assemble');assert.equal(phaseOf(a),1);});
test('Work prerequisites cannot be bypassed',()=>{assert.throws(()=>act(freshAdventure(),'gem'));assert.throws(()=>act(freshAdventure(),'circuit'));assert.throws(()=>act(run(3),'valve'));assert.throws(()=>act(run(4),'night'));});
test('Rooftop placement is an actual three-panel task',()=>{let a=run(1);a=act(a,'panels');a=act(a,'panel1');a=act(a,'shade');assert.ok(!actionsFor(a).some(x=>x.id==='gem'));a=act(a,'panel2');a=act(a,'gem');assert.equal(a.rules.decisions.at(-1).id,'tower');});
test('River scanning requires all three distinct clues',()=>{let a=run(3);a=act(a,'scan1');a=act(a,'scan2');assert.ok(!actionsFor(a).some(x=>x.id==='valve'));a=act(a,'scan3');assert.ok(actionsFor(a).some(x=>x.id==='valve'));});
test('Physical stations enforce budget and a failed night test needs repair or override',()=>{let a=run(4);for(const id of ['cargo','depotDelivery','clinicDelivery','budget:buses','budget:cycling','budget:training','night'])a=act(a,id);assert.equal(a.night.ending,'critical');assert.ok(!actionsFor(a).some(x=>x.id==='gem'));assert.ok(actionsFor(a).some(x=>x.id==='override'));a=act(a,'budget:backup');assert.equal(a.night,null);assert.throws(()=>act(a,'budget:roads'));a=act(a,'night');assert.equal(a.night.ending,'green');});
test('Override remains a meaningful critical ending',()=>{let a=run(4);for(const id of ['cargo','depotDelivery','clinicDelivery','budget:buses','night','override','lift','assemble','activate'])a=act(a,id);assert.equal(a.ending.ending,'critical');});
test('Adventure checkpoint restores carried and installed stones',()=>{let a=run(2);for(const id of missions[2])a=act(a,id);const r=restoreAdventure(JSON.stringify(a));assert.equal(r.stone,2);assert.deepEqual(r.assembled,[0,1]);assert.equal(r.rules.stage,3);assert.equal(restoreAdventure('{'),null);assert.equal(restoreAdventure(JSON.stringify({...a,assembled:[1,0]})),null);});

test('Carrying a rooftop stone preserves the descent ladder',()=>{let a=run(1);for(const id of missions[1])a=act(a,id);assert.ok(actionsFor(a).some(x=>x.id==='ladder'));assert.equal(actionsFor(act(a,'lift')).find(x=>x.id==='assemble').y,-24);});
