import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,decide,assess,replay,restore,budgetTotal} from '../src/rules.js';
import verdict from '../api/verdict.js';
function run(ids=['efficiency','school','infill','effluent']){let s=fresh();['energy','solar','land','river'].forEach((stage,i)=>s=decide(s,stage,ids[i]));return s;}
test('Story plan passes every gate',()=>{const r=assess(run(),['buses','cycling','backup','training']);assert.equal(r.ending,'green');assert.equal(r.total,100);assert.equal(r.reserve,14);assert.ok(Object.values(r.checks).every(Boolean));});
test('Green emissions cannot hide clinic failure',()=>{const r=assess(run(),['buses','cycling','training']);assert.equal(r.checks.carbon,true);assert.equal(r.checks.clinic,false);assert.equal(r.ending,'critical');});
test('Worker support is independent',()=>{const r=assess(run(['closure','school','infill','effluent']),['cycling','backup']);assert.equal(r.checks.workers,false);assert.equal(r.ending,'critical');});
test('Safe but weak climate plan earns survival',()=>assert.equal(assess(run(['coal','mall','clear','plastic']),['cycling','backup','training']).ending,'survival'));
test('Litter removal does not verify effluent control',()=>assert.equal(assess(run(['efficiency','school','infill','plastic']),['buses','cycling','backup','training']).ending,'survival'));
test('Budget rejects overspend, duplicates and inventions',()=>{assert.throws(()=>assess(run(),['buses','roads','petrol']));assert.throws(()=>assess(run(),['backup','backup']));assert.throws(()=>assess(run(),['magic']));});
test('Saves reconstruct scores and reject corruption',()=>{const s=run();s.carbon=0;s.scores=[999];const r=restore(JSON.stringify(s));assert.equal(r.carbon,44);assert.equal(r.scores[0],180);assert.equal(restore('{'),null);assert.equal(restore(JSON.stringify({...s,decisions:[{stage:'river',id:'effluent'}]})),null);});
test('Team turns award points separately',()=>{let s=fresh(4);['energy','solar','land','river'].forEach((k,i)=>s=decide(s,k,['efficiency','school','infill','effluent'][i]));assert.deepEqual(s.scores,[120,120,120,120]);});
test('Server recomputes verdict, ignores client meters',()=>{let status,body;const res={setHeader(){},status(s){status=s;return this;},json(b){body=b;}};verdict({method:'POST',headers:{},body:{decisions:run().decisions,budget:['buses','cycling','training'],players:1,reserve:100}},res);assert.equal(status,200);assert.equal(body.ending,'critical');verdict({method:'POST',headers:{},body:{decisions:[],budget:[],players:1}},res);assert.equal(status,400);verdict({method:'GET',headers:{}},res);assert.equal(status,405);});
test('All legal plans produce bounded deterministic endings',()=>{const sets=[['efficiency','coal','closure'],['school','mall','tower'],['infill','clear','block'],['effluent','plastic','runoff']];const ids=['buses','cycling','backup','training','roads','petrol'];let count=0;for(const a of sets[0])for(const b of sets[1])for(const c of sets[2])for(const d of sets[3])for(let mask=1;mask<64;mask++){const budget=ids.filter((_,i)=>mask&(1<<i));if(budgetTotal(budget)>100)continue;const s=run([a,b,c,d]),r=assess(s,budget);assert.deepEqual(r,assess(replay(s.decisions),budget));assert.ok(['green','survival','critical'].includes(r.ending));assert.ok(r.carbon>=0&&r.carbon<=100);count++;}assert.ok(count>2000);});
