import {LAB_X,LAB_Z,lift,districts,roads,LAB_Y,spawn} from './layout.js';
import {questSteps} from './quest.js';
import {createWorld} from './world.js';
import {audio} from './audio.js';
import {assess,budgetTotal} from './rules.js';
import {freshAdventure,restoreAdventure,actionsFor,act,phaseOf,stoneColors} from './adventure.js';
import {t,setLocale,currentLocale} from './locale.js';
import './adventure-locale.js';
import './expansion-locale.js';
const $=s=>document.querySelector(s),ui=$('#ui'),hud=$('#hud'),music=audio(),semantic=$('#game-state');
let cineStage='',a=freshAdventure(),settings={quality:'high',locale:'en',text:false,volume:.35},screen='home',previous='city',running=false,world,frameInfo={},busy=false,work=0,workId='',releaseNeeded=false,radioUntil=0,toastTimer,events=[],introTime=0,serverChecked=false,taskBeat=0,heatCooldown=0,workLatch=false;
try{Object.assign(settings,JSON.parse(localStorage.getItem('m2050.v3.settings')||'{}'));a=restoreAdventure(localStorage.getItem('m2050.adventure.v3'))||a;}catch{}
setLocale(settings.locale);$('#locale').value=settings.locale;music.volume(settings.volume);
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}const tr=k=>esc(t(k));
function event(name,props={}){events.push({name,...props,locale:currentLocale(),at:Math.round(performance.now())});if(events.length>200)events.shift();window.dispatchEvent(new CustomEvent('mission2050:event',{detail:events.at(-1)}));}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2700);}
function radio(key,duration=8){$('#radio').textContent=t(key)===key?t('adv.taskdone'):t(key);radioUntil=performance.now()+duration*1000;$('#radio').classList.add('visible');}
function persist(){if(world)a.position=world.position();try{localStorage.setItem('m2050.adventure.v3',JSON.stringify(a));localStorage.setItem('m2050.v3.settings',JSON.stringify(settings));}catch{event('save.failure');}}
function snapshot(){return {version:3,screen,adventure:a,nearest:frameInfo.nearest,driving:frameInfo.driving,position:world?.position(),modelLoaded:frameInfo.modelLoaded,nativeRig:frameInfo.nativeRig,securityGuards:frameInfo.securityGuards,traffic:frameInfo.traffic,renderStats:frameInfo.stats,cinematic:frameInfo.cinematic,locale:currentLocale(),events};}
function sync(){world?.update(a,actionsFor(a));semantic.textContent=JSON.stringify(snapshot());document.body.dataset.screen=screen;document.body.dataset.phase=phaseOf(a);renderHUD();}
function button(key,id,cls=''){return `<button data-action="${id}" class="${cls}">${tr(key)}</button>`;}
function modal(content){return `<div class="modalwrap"><section class="panel" role="dialog" aria-modal="true" aria-labelledby="paneltitle" tabindex="-1">${content}</section></div>`;}
function show(next){screen=next;world?.pause(!['city','cinematic','intro'].includes(next));render();if($('.panel'))queueMicrotask(()=>$('.panel')?.focus());}
function renderHUD(){const phase=phaseOf(a),values=a.ending||a.night||(phase===4?assess(a.rules,a.rules.budget):a.rules);$('#locationlabel').textContent=t(a.location==='lab'?'adv.lab':'adv.city')+' · '+t('adv.level')+' '+Math.min(5,a.assembled.length+1)+'/5';$('#queststeps').innerHTML=questSteps(a).map(x=>`<div class="queststep ${x.done?'done':''}"><span>${x.done?'✓':'○'}</span>${tr(x.key)}</div>`).join('');$('#day').textContent=`${t('ui.day')} ${[4,9,15,21,29][phase]} / 30 · ${t('adv.sockets')} ${a.assembled.length}/5`;$('#objective').textContent=t(a.location==='lab'?(a.stone>=0?'adv.labHandover':a.assembled.length===5?'adv.activateReady':'adv.exitLab'):a.assembled.length===5?'adv.ready':a.stone>=0?'adv.return':'phase.'+phase);$('#hint').textContent=a.stone>=0?t('stone.'+a.stone):t(a.location==='lab'?(a.assembled.length===5?'act.activate':'act.liftUp'):actionsFor(a)[0]?.key||'adv.ready');$('#controls').textContent=t('adv.controls');$('#mapBtn').textContent=t('adv.map');$('#pauseBtn').textContent=t('ui.pause');$('#corebar').innerHTML=Array.from({length:5},(_,i)=>`<div class="stonebadge ${a.assembled.includes(i)?'assembled':a.stone===i?'carrying':''}" style="--stone:#${stoneColors[i].toString(16).padStart(6,'0')}" title="${tr('stone.'+i)}"><span>◆</span><small>${i+1}</small></div>`).join('');$('#carrylabel').textContent=a.stone>=0?t('adv.carry')+' / '+t('stone.'+a.stone):a.inventory?t('adv.carry')+' / '+a.inventory.toUpperCase():'';$('#meters').innerHTML=[['ui.carbon',values.carbon],['ui.energy',values.energy],['ui.eco',values.ecosystem],['adv.heat',Math.round(a.heat)]].map(([k,v])=>`<div class="meter"><label>${tr(k)}<b>${v}</b></label><div class="track"><div class="fill" style="width:${Math.min(100,v)}%"></div></div></div>`).join('');if(phase===4)$('#tasktrack').textContent=t('adv.budget')+' / '+budgetTotal(a.rules.budget)+' / 100 · '+t('adv.nightReserve')+' '+values.reserve+' / 10';else $('#tasktrack').textContent='';}
function render(){hud.hidden=!running;document.body.classList.toggle('textmode',settings.text);sync();let html='';
 if(screen==='home')html=`<section class="hero"><div class="eyebrow">${tr('adv.hero')}</div><h1>MISSION<span>2050</span></h1><div class="subtitle">${tr('hero.sub')}</div><p>${tr('adv.desc')}</p><div class="actions">${button(a.tasks.length||a.assembled.length?'adv.continue':'adv.start','begin','primary')}${button('adv.guide','guide')}</div><div class="tagrow">${tr('adv.tag')}</div></section><div class="herofooter">${tr('adv.subtitle')}</div><div class="coordinates">SURYANAGAR / 49°C<br>FIVE STONES. ONE CITY.</div>`;
 if(screen==='guide')html=modal(`<h2 id="paneltitle">${tr('adv.guide')}</h2><p>${tr('adv.guidebody')}</p><p>${tr('adv.guidewin')}</p><p class="caption">${tr('adv.credits')}</p><div class="actions">${button('ui.close','return','primary')}</div>`);
 if(screen==='pause')html=modal(`<div class="eyebrow">FIELD OPERATIONS / PAUSED</div><h2 id="paneltitle">${tr('adv.pause')}</h2><div class="actions">${button('ui.resume','city','primary')}${button('adv.guide','guide')}${button('adv.new','restart')}</div>`);
 if(screen==='settings')html=modal(`<h2 id="paneltitle">${tr('settings.title')}</h2><label class="settingsrow">${tr('settings.quality')}<select id="quality"><option value="high" ${settings.quality==='high'?'selected':''}>${tr('settings.high')}</option><option value="low" ${settings.quality==='low'?'selected':''}>${tr('settings.low')}</option></select></label><label class="settingsrow">${tr('adv.settingsText')}<input id="textmode" type="checkbox" ${settings.text?'checked':''}></label><label class="settingsrow">${tr('settings.volume')}<input id="volume" type="range" min="0" max="1" step=".05" value="${settings.volume}"></label><div class="actions">${button('ui.close','return','primary')}</div>`);
 if(screen==='map')html=modal(`<div class="eyebrow">FIELD NAVIGATION</div><h2 id="paneltitle">${tr('adv.map')}</h2><canvas id="bigmap" width="600" height="420"></canvas><p>${tr('adv.mapdesc')}</p><div class="waypoints">${actionsFor(a).map(x=>`<span>${tr(x.key)} · ${Math.round(Math.hypot((a.position[0]||0)-x.x,(a.position[2]||16)-x.z))} m</span>`).join('')}</div><div class="actions">${button('ui.close','city','primary')}</div>`);
 if(screen==='ending'){const r=a.ending;html=modal(`<div class="eyebrow">${tr('adv.finished')} / ECO-CORE</div><h1 id="paneltitle" class="endtitle">${tr('ending.'+r.ending)}</h1><p class="dialogue">${tr('ending.'+r.ending+'body')}</p><div class="eyebrow">${tr('ending.refrain')}</div><div class="statgrid"><div class="stat"><b>${r.carbon}</b>${tr('ui.carbon')}</div><div class="stat"><b>${r.energy}</b>${tr('ui.energy')}</div><div class="stat"><b>${r.ecosystem}</b>${tr('ui.eco')}</div></div><p>${tr('adv.nightReserve')}: ${r.reserve} / 10</p><p class="caption">${tr(serverChecked?'ui.server':'ui.local')}</p><div class="actions">${button('adv.new','restart','primary')}${button('adv.retry','retry')}</div><p class="caption">${tr('ui.detail')}</p>`);}
 if(settings.text&&screen==='city')html=modal(`<h2 id="paneltitle">${tr('adv.textmode')}</h2><p>${tr('adv.textdesc')}</p><div class="choices">${actionsFor(a).filter(x=>x.id!=='ladder').map(x=>`<button class="choice" data-action="accessible:${x.id}">${tr(x.key)}</button>`).join('')}</div>`);
 ui.innerHTML=html;$('#quality')?.addEventListener('change',e=>{settings.quality=e.target.value;world.quality(settings.quality);persist();});$('#textmode')?.addEventListener('change',e=>{settings.text=e.target.checked;world.text(settings.text);persist();});$('#volume')?.addEventListener('input',e=>{settings.volume=Number(e.target.value);music.volume(settings.volume);persist();});if($('#bigmap'))drawMap($('#bigmap'),true);event('menu.view',{screen});}
function drawMap(canvas,big=false){
 const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,pos=world?.position()||a.position,indoor=a.location==='lab',extent=indoor?45:big?650:135,scale=Math.min(w,h)/extent;
 ctx.fillStyle='#0b1822';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);ctx.scale(scale,scale);ctx.translate(indoor?-LAB_X:big?0:-pos[0],indoor?5-LAB_Z:big?0:-pos[2]);
 if(indoor){ctx.save();ctx.translate(LAB_X,LAB_Z);ctx.fillStyle='#274352';ctx.fillRect(-18,-22,36,34);ctx.strokeStyle='#6a909c';ctx.lineWidth=.15;ctx.strokeRect(-18,-22,36,34);ctx.fillStyle='#84dfdb';ctx.beginPath();ctx.arc(0,-8,3.4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d9dfe5';ctx.fillRect(-3,6,6,5);ctx.restore();}
 else{ctx.fillStyle='#152532';ctx.fillRect(-300,-300,600,600);for(const [i,d] of districts.entries()){ctx.fillStyle=i<=phaseOf(a)?'#233c43':'#121e29';ctx.beginPath();ctx.arc(...d.center,d.radius,0,Math.PI*2);ctx.fill();ctx.strokeStyle=i<=phaseOf(a)?'#50716e':'#293541';ctx.lineWidth=big?1:.3;ctx.stroke();}ctx.save();ctx.beginPath();ctx.arc(0,0,42,0,Math.PI*2);for(let i=0;i<=phaseOf(a);i++){const d=districts[i];ctx.moveTo(d.center[0]+d.radius,d.center[1]);ctx.arc(...d.center,d.radius,0,Math.PI*2);const l=Math.hypot(...d.center),nx=-d.center[1]/l*12,nz=d.center[0]/l*12;ctx.moveTo(nx,nz);ctx.lineTo(d.center[0]+nx,d.center[1]+nz);ctx.lineTo(d.center[0]-nx,d.center[1]-nz);ctx.lineTo(-nx,-nz);ctx.closePath();}ctx.clip();ctx.fillStyle='#52636a';for(const r of roads){ctx.fillRect(r-7,-330,14,660);ctx.fillRect(-330,r-7,660,14);}ctx.fillStyle='#456953';ctx.fillRect(86,-146,58,56);ctx.fillStyle='#326b78';ctx.fillRect(232,6,24,128);ctx.restore();ctx.fillStyle='#8ddeef';ctx.fillRect(LAB_X-5,LAB_Z,10,12);if(big){ctx.font='11px Arial';for(const [i,d] of districts.entries()){ctx.fillStyle=i<=phaseOf(a)?'#e3d4b5':'#788594';ctx.textAlign='center';ctx.fillText(t(d.key)+(i>phaseOf(a)?' · '+t('adv.locked'):''),d.center[0],d.center[1]-12);}}}
 const nav=frameInfo.route||[];if(nav.length){ctx.strokeStyle='#e9c384';ctx.lineWidth=indoor?.14:big?1:1.2;ctx.beginPath();nav.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();}
 for(const item of actionsFor(a)){ctx.fillStyle=item.kind==='gem'?'#8aead9':item.id==='lift'?'#7ac9e6':'#ecc385';ctx.beginPath();ctx.arc(item.x,item.z,indoor?.35:big?2.6:1.7,0,Math.PI*2);ctx.fill();}
 ctx.translate(pos[0],pos[2]);ctx.rotate(-(frameInfo.yaw||0));ctx.fillStyle='#ffffff';const n=indoor?.6:big?3:2;ctx.beginPath();ctx.moveTo(0,-n);ctx.lineTo(n*.7,n);ctx.lineTo(-n*.7,n);ctx.closePath();ctx.fill();ctx.restore();
}
async function perform(id,accessible=false){if(busy)return;const item=actionsFor(a).find(x=>x.id===id);if(!item)return;if(!accessible&&frameInfo.nearest?.id!==id)return;
 if(id==='brief'){radio('adv.labBrief',12);music.effect('work');return;}
 if(id==='ladder'){releaseNeeded=true;work=0;workLatch=false;world.climb();music.effect('work');return;}
 if(item.kind==='deliver'&&!frameInfo.driving&&!accessible){toast(t('adv.carNeed'));return;}
 busy=true;world.working?.(false);workLatch=false;releaseNeeded=true;work=0;try{
 if(id==='lift'){screen='elevator';$('#cinematic').classList.add('on');$('#cineTitle').textContent=t('adv.lab');$('#cineSubtitle').textContent=t(a.location==='city'?'cine.descent':'cine.ascent');world.pause(true);music.effect('elevator');event('elevator.start');if(!settings.text)await world.elevator(a.location==='city');a=act(a,id);if(settings.text)world.start(a.position);screen='city';world.pause(false);$('#cinematic').classList.remove('on');radio(a.location==='lab'?'adv.labArrival':'adv.surfaceArrival');event('elevator.complete');}
 else if(id==='assemble'){const index=a.stone;screen='cinematic';$('#cinematic').classList.add('on');$('#cineTitle').textContent=t('stone.'+index);$('#cineSubtitle').textContent=t('adv.assembly');world.pause(true);music.effect('handover',index);event('assembly.start',{index});if(!settings.text)await world.assemble(index);a=act(a,id);screen='city';world.pause(false);$('#cinematic').classList.remove('on');radio(a.assembled.length===5?'radio.coreReady':'radio.assemble');$('#unlock').textContent=t(a.assembled.length===5?'adv.allStones':'adv.unlocked')+' · '+t(districts[Math.min(4,a.assembled.length)].key);$('#unlock').classList.add('visible');setTimeout(()=>$('#unlock').classList.remove('visible'),6000);music.effect('unlock');event('assembly.complete',{index});}
 else if(id==='activate'){a=act(a,id);screen='finale';world.pause(true);$('#cinematic').classList.add('on');$('#cineTitle').textContent=t('adv.finished');$('#cineSubtitle').textContent=t('adv.subtitle');const finale=world.activate(a.ending.ending);music.effect('reactor');try{const res=await fetch('/api/verdict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decisions:a.rules.decisions,players:a.rules.scores.length,budget:a.rules.budget}),signal:AbortSignal.timeout(5000)});if(res.ok){a.ending=await res.json();serverChecked=true;}}catch{serverChecked=false;}if(!settings.text)await finale;$('#cinematic').classList.remove('on');event('ending.view',{ending:a.ending.ending});show('ending');}
 else{a=act(a,id);event(item.kind==='gem'?'stone.collect':'task.complete',{id,phase:phaseOf(a)});if(id==='gem'||id==='override'){music.effect('collect',a.stone);radio('adv.return');}else if(id==='night'){radio(a.night.ending==='critical'?'adv.fail':'adv.safe',12);music.effect(a.night.ending==='critical'?'error':'collect',4);}else if(id.startsWith('budget:')){toast(t(item.key)+(a.rules.budget.includes(id.slice(7))?' ✓':' ×'));music.effect('click');}else{music.effect('work');const key=id.startsWith('panel')&&id!=='panels'?'radio.panel':id.startsWith('water')?'radio.water':'radio.'+id;radio(key);}}
 persist();sync();if(settings.text)render();
 }catch(e){toast(t('adv.overbudget'));music.effect('error');event('action.rejected',{id,message:e.message});}finally{busy=false;}}
function tick(dt,info){frameInfo=info;document.body.dataset.cinematicStep=info.cinematic?Math.floor(info.cinematic.progress*10):'';document.body.dataset.playerX=info.position[0].toFixed(2);document.body.dataset.playerY=info.position[1].toFixed(2);document.body.dataset.playerZ=info.position[2].toFixed(2);document.body.dataset.modelLoaded=String(info.modelLoaded);document.body.dataset.driving=String(info.driving);if(performance.now()>radioUntil)$('#radio').classList.remove('visible');
 if(screen==='intro'){introTime+=dt;if(introTime>5&&introTime<5+dt*2)radio('adv.intro2');if(introTime>10&&introTime<10+dt*2)radio('adv.intro3');if(introTime>15){$('#cinematic').classList.remove('on','intro');show('city');}return;}
 if(screen!=='city')return;const item=info.nearest;$('#targetname').textContent=item?t(item.key):t('adv.ready');$('#distance').textContent=item?Math.round(item.distance)+' '+t('adv.distance'):'';$('#bearing').textContent='➤';if(item){const angle=Math.atan2(item.x-info.position[0],-(item.z-info.position[2]))-info.yaw;$('#bearing').style.transform=`rotate(${angle}rad)`;}const help=item?.id==='lift'&&a.location==='lab'?'help.liftUp':item?.id.startsWith('budget:')?'help.budget':'help.'+item?.id;$('#taskhelp').textContent=t(help)===help?t('help.default'):t(help);
 const inRange=item&&item.distance<(info.driving?3:2.2);$('#prompt').classList.toggle('visible',!!inRange);$('#interactlabel').textContent=inRange?t('adv.hold')+' '+(item.kind==='scan'?'Q / E':'E')+' · '+t(item.key):'';
 const held=workLatch||world.keys.has('e')||world.keys.has('E')||(item?.kind==='scan'&&world.keys.has('q'));world.working?.(held&&inRange&&!busy);if(!inRange){workLatch=false;work=0;}if(inRange&&held&&!releaseNeeded&&!busy){if(workId!==item.id){workId=item.id;work=0;}work+=dt/item.duration;$('#workfill').style.width=Math.min(100,work*100)+'%';if(work>=1)perform(item.id);}else if(!held){work=0;workId='';releaseNeeded=false;$('#workfill').style.width='0%';}
 // Heat is immediate survival pressure; shade and the lab are safe cooling spaces.
 const cool=a.location==='lab'||Math.hypot(info.position[0]-lift[0],info.position[2]-lift[1])<15||Math.hypot(info.position[0]-112,info.position[2]+109)<35||Math.hypot(info.position[0]+53,info.position[2]-30)<12;if(heatCooldown>0){heatCooldown-=dt;a.heat=Math.max(0,a.heat-dt*10);}else a.heat=Math.max(0,Math.min(100,a.heat+dt*(cool?-5:info.driving?.12:world.keys.has('Shift')?1.2:.2)));$('#damage').style.opacity=Math.max(0,(a.heat-65)/60);if(a.heat>=100){a.location='city';world.start(spawn);world.pause(false);a.heat=45;heatCooldown=8;work=0;toast(t('adv.exhausted'));music.effect('error');event('player.heat_exhaustion');persist();}
 taskBeat+=dt;if(taskBeat>.2){taskBeat=0;drawMap($('#minimap'));renderHUD();semantic.textContent=JSON.stringify(snapshot());}if(info.driving)$('#distance').textContent+=` / ${Math.round(info.speed)} ${t('adv.speed')}`;
}
try{world=createWorld($('#world'),fps=>$('#fps').textContent=settings.text?t('adv.textmode'):fps+' FPS');world.hooks(tick,(name,props)=>{if(name==='footstep')music.effect('footstep');else if(name==='scanner')music.effect('scanner');else if(name==='vehicle.bump')music.effect('error');else if(name==='traffic.hit'){a.heat=Math.min(100,a.heat+18);toast(t('adv.traffic'));music.effect('error');event('player.traffic_hit');}else if(name==='district.locked'){toast(t('adv.lockedHelp'));music.effect('error');}else if(name==='cinematic.stage'){if(props.id!==cineStage){cineStage=props.id;$('#cineSubtitle').textContent=t('cine.'+props.id);if(props.id==='activation')music.effect('assemble',a.stone);if(props.id==='doorsClose'||props.id==='doorsOpen'||props.id==='surfaceOpen')music.effect('door');event('cinematic.stage',{id:props.id});}}else if(name==='models.ready')event(name);});world.quality(settings.quality);world.text(settings.text);}catch(e){settings.text=true;world={keys:new Set(),hooks(){},update(){},pause(){},start(){},stop(){},position:()=>a.position,text(){},quality(){},activate:()=>Promise.resolve(),scan(){},camera(){},jump(){},vehicle:()=>false};event('renderer.unavailable',{message:e.message});}
async function begin(){running=true;world.start(a.tasks.length||a.assembled.length?a.position:spawn);if(!music.enabled()){try{await music.toggle();$('#sound').textContent='♪ ON';}catch{}}if(a.ending){show('ending');}else if(a.tasks.length||a.assembled.length){show('city');radio(a.location==='lab'?(a.stone>=0?'adv.labArrival':'adv.exitLab'):a.stone>=0?'adv.return':'adv.intro3');}else{show(settings.text?'city':'intro');introTime=0;radio('adv.intro1');if(!settings.text){$('#cinematic').classList.add('on','intro');$('#cineTitle').textContent=t('adv.subtitle');$('#cineSubtitle').textContent=t('adv.skip');}}event('adventure.start');persist();}
ui.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const id=b.dataset.action;if(id==='begin')begin();else if(id==='city')show('city');else if(id==='return')show(previous);else if(id==='guide'){previous=screen;show('guide');}else if(id==='restart'){a=freshAdventure();running=false;world.start(a.position);world.stop();persist();$('#cinematic').classList.remove('on','intro');show('home');}else if(id==='retry'){a.ending=null;if(a.assembled.length===5)a.assembled.pop();a.stone=-1;a.inventory='';a.night=null;a.location='city';world.start([-121,0,191]);running=true;show('city');persist();}else if(id.startsWith('accessible:'))perform(id.slice(11),true);});
$('#settings').addEventListener('click',()=>{previous=screen;show('settings');});$('#pauseBtn').addEventListener('click',()=>{persist();show('pause');});$('#mapBtn').addEventListener('click',()=>show('map'));$('#locale').addEventListener('change',e=>{settings.locale=e.target.value;setLocale(settings.locale);persist();render();});$('#sound').addEventListener('click',async()=>{try{$('#sound').textContent=await music.toggle()?'♪ ON':'♪ OFF';}catch{}});
function vehicle(){if(world.vehicle()){music.effect('vehicle');event('vehicle.toggle');}else toast(t('adv.carNeed'));}
addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(screen==='intro'&&e.key==='Enter'){$('#cinematic').classList.remove('on','intro');show('city');return;}if(screen==='city'){if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Shift','e','E','q',' '].includes(e.key)){e.preventDefault();world.keys.add(e.key);}if(!e.repeat){if(e.key.toLowerCase()==='f')vehicle();if(e.key.toLowerCase()==='c')world.camera();if(e.key.toLowerCase()==='q')world.scan();if(e.key===' ')world.jump();if(e.key.toLowerCase()==='m')show('map');}}
 if(e.key==='Escape'){e.preventDefault();if(screen==='city'){persist();show('pause');}else if(['pause','map','guide','settings'].includes(screen))show(running?'city':'home');}if(e.key==='Tab'&&$('.panel')){const items=[...$('.panel').querySelectorAll('button,select,input')];if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('.panel'))){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
addEventListener('keyup',e=>{world.keys.delete(e.key);if(['e','E','q'].includes(e.key))releaseNeeded=false;});addEventListener('blur',()=>world.keys.clear());document.addEventListener('visibilitychange',()=>{world.keys.clear();if(document.hidden){persist();music.suspend();}else music.resume();});addEventListener('pagehide',persist);
for(const b of document.querySelectorAll('[data-move]')){const key={up:'w',down:'s',left:'a',right:'d'}[b.dataset.move];b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);b.dataset.down=performance.now();b.dataset.held='1';world.keys.add(key);});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>{if(b.dataset.held!=='1')return;b.dataset.held='0';world.keys.delete(key);if(name==='pointerup'&&performance.now()-Number(b.dataset.down)<180)world.moveFor(key,.45);});}
$('#interactTouch').addEventListener('click',()=>{workLatch=!workLatch;releaseNeeded=false;});$('#interactTouch').addEventListener('pointerdown',e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);world.keys.add('e');releaseNeeded=false;});for(const name of ['pointerup','pointercancel','lostpointercapture'])$('#interactTouch').addEventListener(name,()=>{world.keys.delete('e');releaseNeeded=false;});$('#cameraTouch').onclick=()=>world.camera();$('#vehicleTouch').onclick=vehicle;$('#scanTouch').onclick=()=>world.scan();$('#jumpTouch').onclick=()=>world.jump();
setInterval(()=>{if(running&&screen==='city')persist();},5000);Object.defineProperty(window,'mission2050',{value:Object.freeze({snapshot:()=>structuredClone(snapshot())})});render();event('app.ready');
