import {navigationColour,routeLength} from './navigation-target.js';
import {createNavigationCompass,worldBearing,mapPoint} from './navigation-hud.js';
import {gameplayKey,compassHeading,routeDirection,remainingRoute} from './input.js';
import {LAB_X,LAB_Z,lift,districts,roads,LAB_Y,spawn,serviceConnections,buildingLots,treeSites} from './layout.js';
import {questSteps} from './quest.js';
import {createWorld} from './world.js';
import {audio} from './audio.js';
import {createConversation,detectCharacter} from './conversation.js';
import {assess,budgetTotal} from './rules.js';
import {freshAdventure,restoreAdventure,actionsFor,act,phaseOf,stoneColors} from './adventure.js';
import {t,setLocale,currentLocale} from './locale.js';
import './adventure-locale.js';
import './expansion-locale.js';
import './navigation-locale.js';
const $=s=>document.querySelector(s),ui=$('#ui'),hud=$('#hud'),music=audio(),semantic=$('#game-state');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,conversation=createConversation($('#radio'),hz=>music.effect('conversation_blip',hz),{reduced,speak:(text,who)=>music.speak(text,who),silence:()=>music.silence()});
const explored=new Set(),trail=[],mapView={zoom:1,x:0,z:0},compass=createNavigationCompass($('#compass'));let mapPin=null;
let audioBeat=0,progressBand=-1,trafficSoundTime=0;
let cineStage='',a=freshAdventure(),settings={quality:'balanced',locale:'en',text:false,volume:.8},screen='home',previous='city',running=false,world,frameInfo={},busy=false,work=0,workId='',releaseNeeded=false,toastTimer,events=[],introTime=0,serverChecked=false,taskBeat=0,heatCooldown=0,workLatch=false;
try{Object.assign(settings,JSON.parse(localStorage.getItem('m2050.v3.settings')||'{}'));a=restoreAdventure(localStorage.getItem('m2050.adventure.v3'))||a;const visited=JSON.parse(localStorage.getItem('m2050.explored.v3')||'[]');if(Array.isArray(visited))for(const cell of visited.slice(0,1600))if(typeof cell==='string'&&/^-?\d+,-?\d+$/.test(cell))explored.add(cell);}catch{}
if(settings.audioVersion!==1){settings.volume=.8;settings.audioVersion=1;}
if(settings.renderVersion!==2){settings.quality='balanced';settings.renderVersion=2;}
setLocale(settings.locale);$('#locale').value=settings.locale;music.volume(settings.volume);
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}const tr=k=>esc(t(k));
function event(name,props={}){events.push({name,...props,locale:currentLocale(),at:Math.round(performance.now())});if(events.length>200)events.shift();window.dispatchEvent(new CustomEvent('mission2050:event',{detail:events.at(-1)}));}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2700);}
function radio(key,duration=8){conversation.cancel();const actual=t(key)===key?'adv.taskdone':key;music.effect('radio_static');conversation.play([{key:actual,who:actual.startsWith('conv.')?detectCharacter(t(actual)):actual==='adv.intro1'?'asha':actual==='adv.intro2'?'kabir':['adv.intro3','adv.labBrief','radio.assemble','radio.coreReady'].includes(actual)?'meera':detectCharacter(t(actual)),hold:Math.max(Math.min(4,duration/2),t(actual).length*(1/17-1/35))}]);}
function persist(){if(world){a.position=world.position();if(world.vehicleState)a.vehicle=world.vehicleState();}try{localStorage.setItem('m2050.adventure.v3',JSON.stringify(a));localStorage.setItem('m2050.v3.settings',JSON.stringify(settings));localStorage.setItem('m2050.explored.v3',JSON.stringify([...explored]));}catch{event('save.failure');}}
function snapshot(){return {version:3,screen,adventure:a,nearest:frameInfo.nearest,driving:frameInfo.driving,facing:frameInfo.facing,climbing:frameInfo.climbing,navigationTarget:frameInfo.navigationTarget,route:frameInfo.route,routeStatus:frameInfo.routeStatus,position:world?.position(),modelLoaded:frameInfo.modelLoaded,nativeRig:frameInfo.nativeRig,securityGuards:frameInfo.securityGuards,traffic:frameInfo.traffic,renderStats:frameInfo.stats,cinematic:frameInfo.cinematic,locale:currentLocale(),events};}
function sync(){world?.update(a,actionsFor(a));semantic.textContent=JSON.stringify(snapshot());document.body.dataset.screen=screen;document.body.dataset.phase=phaseOf(a);renderHUD();}
function button(key,id,cls=''){return `<button data-action="${id}" class="${cls}">${tr(key)}</button>`;}
function modal(content){return `<div class="modalwrap ${screen==='map'?'mapwrap':''}"><section class="panel ${screen==='map'?'tactical-map':''}" role="dialog" aria-modal="true" aria-labelledby="paneltitle" tabindex="-1">${content}</section></div>`;}
function show(next){screen=next;if(next==='ending'){$('#unlock').classList.remove('visible');$('#toast').classList.remove('show');}world?.intro?.(next==='intro');if(!['city','cinematic','intro','ending'].includes(next))music.scene({active:false});world?.pause(!['city','cinematic','intro'].includes(next));render();if($('.panel'))queueMicrotask(()=>$('.panel')?.focus());}
let questPinned=false,questTimer;
function activityBoard(open){$('#missionbox').classList.toggle('expanded',open);$('#questToggle').setAttribute('aria-expanded',String(open));$('#questToggle').textContent=t(open?'nav.activitiesClose':'nav.activities');}
function revealActivity(){clearTimeout(questTimer);activityBoard(true);questTimer=setTimeout(()=>{if(!questPinned)activityBoard(false);},5000);}
function renderHUD(){ $('#questToggle').textContent=t($('#missionbox').classList.contains('expanded')?'nav.activitiesClose':'nav.activities');$('#minimapToggle').setAttribute('aria-label',t('nav.mapToggle'));$('#compass').setAttribute('aria-label',t('nav.compass'));const phase=phaseOf(a),values=a.ending||a.night||(phase===4?assess(a.rules,a.rules.budget):a.rules);$('#locationlabel').textContent=t(a.location==='lab'?'adv.lab':'adv.city')+' · '+t('adv.level')+' '+Math.min(5,a.assembled.length+1)+'/5';$('#queststeps').innerHTML=questSteps(a).map(x=>`<div class="queststep ${x.done?'done':''}"><span>${x.done?'✓':'○'}</span>${tr(x.key)}</div>`).join('');$('#day').textContent=`${t('ui.day')} ${[4,9,15,21,29][phase]} / 30 · ${t('adv.sockets')} ${a.assembled.length}/5`;$('#objective').textContent=t(a.location==='lab'?(a.stone>=0?'adv.labHandover':a.assembled.length===5?'adv.activateReady':'adv.exitLab'):a.assembled.length===5?'adv.ready':a.stone>=0?'adv.return':'phase.'+phase);$('#hint').textContent=a.stone>=0?t('stone.'+a.stone):t(a.location==='lab'?(a.assembled.length===5?'act.activate':'act.liftUp'):actionsFor(a)[0]?.key||'adv.ready');$('#controls').textContent=t('adv.controls');$('#mapBtn').textContent=t('adv.map');$('#pauseBtn').textContent=t('ui.pause');$('#corebar').innerHTML=Array.from({length:5},(_,i)=>`<div class="stonebadge ${a.assembled.includes(i)?'assembled':a.stone===i?'carrying':''}" style="--stone:#${stoneColors[i].toString(16).padStart(6,'0')}" title="${tr('stone.'+i)}"><span>◆</span><small>${i+1}</small></div>`).join('');$('#carrylabel').textContent=a.stone>=0?t('adv.carry')+' / '+t('stone.'+a.stone):a.inventory?t('adv.carry')+' / '+a.inventory.toUpperCase():'';$('#meters').innerHTML=[['ui.carbon',values.carbon],['ui.energy',values.energy],['ui.eco',values.ecosystem],['adv.heat',Math.round(a.heat)]].map(([k,v])=>`<div class="meter"><label>${tr(k)}<b>${v}</b></label><div class="track"><div class="fill" style="width:${Math.min(100,v)}%"></div></div></div>`).join('');if(phase===4)$('#tasktrack').textContent=t('adv.budget')+' / '+budgetTotal(a.rules.budget)+' / 100 · '+t('adv.nightReserve')+' '+values.reserve+' / 10';else $('#tasktrack').textContent='';}
function render(){hud.hidden=!running;document.body.classList.toggle('textmode',settings.text);sync();let html='';
 if(screen==='home')html=`<section class="hero"><div class="eyebrow">${tr('adv.hero')}</div><h1>MISSION<span>2050</span></h1><div class="subtitle">${tr('hero.sub')}</div><p>${tr('adv.desc')}</p><div class="actions">${button(a.tasks.length||a.assembled.length?'adv.continue':'adv.start','begin','primary')}${button('adv.guide','guide')}</div><div class="tagrow">${tr('adv.tag')}</div></section><div class="herofooter">${tr('adv.subtitle')}</div><div class="coordinates">SURYANAGAR / 49°C<br>FIVE STONES. ONE CITY.</div>`;
 if(screen==='guide')html=modal(`<h2 id="paneltitle">${tr('adv.guide')}</h2><p>${tr('adv.guidebody')}</p><p>${tr('adv.guidewin')}</p><p class="caption">${tr('adv.credits')}</p><div class="actions">${button('ui.close','return','primary')}</div>`);
 if(screen==='pause')html=modal(`<div class="eyebrow">FIELD OPERATIONS / PAUSED</div><h2 id="paneltitle">${tr('adv.pause')}</h2><div class="actions">${button('ui.resume','city','primary')}${button('adv.guide','guide')}${button('adv.new','restart')}</div>`);
 if(screen==='settings')html=modal(`<h2 id="paneltitle">${tr('settings.title')}</h2><label class="settingsrow">${tr('settings.quality')}<select id="quality"><option value="balanced" ${settings.quality==='balanced'?'selected':''}>${tr('settings.balanced')}</option><option value="high" ${settings.quality==='high'?'selected':''}>${tr('settings.high')}</option><option value="low" ${settings.quality==='low'?'selected':''}>${tr('settings.low')}</option></select></label><label class="settingsrow">${tr('adv.settingsText')}<input id="textmode" type="checkbox" ${settings.text?'checked':''}></label><label class="settingsrow">${tr('settings.volume')}<input id="volume" type="range" min="0" max="1" step=".05" value="${settings.volume}"></label><div class="actions">${button('ui.close','return','primary')}</div>`);
 if(screen==='map')html=modal(`<div class="eyebrow">${tr('nav.mapTitle')}</div><h2 id="paneltitle">${tr('adv.map')}</h2><canvas id="bigmap" width="720" height="720" tabindex="0"></canvas><div class="actions"><button id="zoomIn">${tr('nav.zoomIn')}</button><button id="zoomOut">${tr('nav.zoomOut')}</button><button id="mapReset">${tr('nav.reset')}</button><button id="clearMapPin">${tr('nav.clearPin')}</button></div><p class="caption">${tr('nav.pinHelp')}</p><p class="caption">${tr('nav.legend')}</p><p>${tr('adv.mapdesc')}</p><div class="waypoints">${actionsFor(a).map(x=>`<button data-map-action="${esc(x.id)}" style="--marker:${navigationColour(x)}">${x.kind==='gem'?'◆':'➤'} ${tr(x.key)} · ${Math.round(Math.hypot((a.position[0]||0)-x.x,(a.position[2]||16)-x.z))} m</button>`).join('')}</div><div class="actions">${button('ui.close','city','primary')}</div>`);
 if(screen==='ending'){const r=a.ending;html=modal(`<div class="eyebrow">${tr('adv.finished')} / ECO-CORE</div><h1 id="paneltitle" class="endtitle">${tr('ending.'+r.ending)}</h1><p class="dialogue">${tr('ending.'+r.ending+'body')}</p><div class="eyebrow">${tr('ending.refrain')}</div><div class="statgrid"><div class="stat"><b>${r.carbon}</b>${tr('ui.carbon')}</div><div class="stat"><b>${r.energy}</b>${tr('ui.energy')}</div><div class="stat"><b>${r.ecosystem}</b>${tr('ui.eco')}</div></div><p>${tr('adv.nightReserve')}: ${r.reserve} / 10</p><p class="caption">${tr(serverChecked?'ui.server':'ui.local')}</p><div class="actions">${button('adv.new','restart','primary')}${button('adv.retry','retry')}</div><p class="caption">${tr('ui.detail')}</p>`);}
 if(settings.text&&screen==='city')html=modal(`<h2 id="paneltitle">${tr('adv.textmode')}</h2><p>${tr('adv.textdesc')}</p><div class="choices">${actionsFor(a).filter(x=>x.id!=='ladder').map(x=>`<button class="choice" data-action="accessible:${x.id}">${tr(x.key)}</button>`).join('')}</div>`);
 ui.innerHTML=html;$('#quality')?.addEventListener('change',e=>{settings.quality=e.target.value;world.quality(settings.quality);persist();});$('#textmode')?.addEventListener('change',e=>{settings.text=e.target.checked;if(!settings.text&&world===textWorld){prepareWorld();if(running){world.start(a.position,a.vehicle);world.update(a,actionsFor(a));world.pause(screen!=='city');}}world.text(settings.text);persist();});$('#volume')?.addEventListener('input',e=>{settings.volume=Number(e.target.value);music.volume(settings.volume);persist();});if($('#bigmap')){drawMap($('#bigmap'),true);bindMap($('#bigmap'));}event('menu.view',{screen});}
function selectMapTarget(target){mapPin=target;world.setNavigationTarget?.(target);Object.assign(frameInfo,world.navigation?.()||{});}
function infoYaw(){return frameInfo.driving?(world.navigation?.().heading||0):(frameInfo.yaw||0);}
function drawMap(canvas,big=false){
 const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,pos=world?.position()||a.position,indoor=a.location==='lab',extent=indoor?45:big?650/mapView.zoom:135,scale=Math.min(w,h)/extent;
 ctx.fillStyle=indoor?'#162831':'#243b29';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);if(!big)ctx.rotate(infoYaw());ctx.scale(scale,scale);ctx.translate(big?(indoor?-LAB_X:-mapView.x):-pos[0],big?(indoor?5-LAB_Z:-mapView.z):-pos[2]);
 if(indoor){ctx.save();ctx.translate(LAB_X,LAB_Z);ctx.fillStyle='#274352';ctx.fillRect(-18,-22,36,34);ctx.strokeStyle='#6a909c';ctx.lineWidth=.15;ctx.strokeRect(-18,-22,36,34);ctx.fillStyle='#84dfdb';ctx.beginPath();ctx.arc(0,-8,3.4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d9dfe5';ctx.fillRect(-3,6,6,5);ctx.restore();}
 else{ctx.fillStyle='#304631';ctx.fillRect(-300,-300,600,600);for(const [i,d] of districts.entries()){ctx.fillStyle=i<=phaseOf(a)?['#4c3c28','#263c53','#274c38','#234c55','#403449'][i]:'#121e29';ctx.beginPath();ctx.arc(...d.center,d.radius,0,Math.PI*2);ctx.fill();ctx.strokeStyle=i<=phaseOf(a)?'#50716e':'#293541';ctx.lineWidth=big?1:.3;ctx.stroke();}ctx.save();ctx.beginPath();ctx.arc(0,0,42,0,Math.PI*2);for(let i=0;i<=phaseOf(a);i++){const d=districts[i];ctx.moveTo(d.center[0]+d.radius,d.center[1]);ctx.arc(...d.center,d.radius,0,Math.PI*2);const l=Math.hypot(...d.center),nx=-d.center[1]/l*12,nz=d.center[0]/l*12;ctx.moveTo(nx,nz);ctx.lineTo(d.center[0]+nx,d.center[1]+nz);ctx.lineTo(d.center[0]-nx,d.center[1]-nz);ctx.lineTo(-nx,-nz);ctx.closePath();}for(const c of serviceConnections){if(c.level>phaseOf(a))continue;const dx=c.to[0]-c.from[0],dz=c.to[1]-c.from[1],l=Math.hypot(dx,dz),nx=-dz/l*12,nz=dx/l*12;ctx.moveTo(c.from[0]+nx,c.from[1]+nz);ctx.lineTo(c.to[0]+nx,c.to[1]+nz);ctx.lineTo(c.to[0]-nx,c.to[1]-nz);ctx.lineTo(c.from[0]-nx,c.from[1]-nz);ctx.closePath();}ctx.clip();ctx.fillStyle='#52636a';ctx.lineWidth=10;for(const c of serviceConnections){if(c.level>phaseOf(a))continue;ctx.strokeStyle='#52636a';ctx.beginPath();ctx.moveTo(...c.from);ctx.lineTo(...c.to);ctx.stroke();}for(const r of roads){ctx.fillRect(r-7,-330,14,660);ctx.fillRect(-330,r-7,660,14);}ctx.fillStyle='#acb398';for(const b of buildingLots)ctx.fillRect(b.x-b.w/2,b.z-b.d/2,b.w,b.d);for(const [x,z,w,d] of [[-59,28,16,18],[-112,-83,22,24],[215,104,18,24],[-142,180,24,18]])ctx.fillRect(x-w/2,z-d/2,w,d);ctx.fillStyle='#456953';ctx.fillRect(86,-146,58,56);ctx.fillStyle='#79a276';for(const [x,z] of treeSites){ctx.beginPath();ctx.arc(x,z,big?2:1.3,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#326b78';ctx.fillRect(232,6,24,128);ctx.restore();ctx.fillStyle='#8ddeef';ctx.fillRect(LAB_X-5,LAB_Z,10,12);}
 if(!indoor){ctx.font=(big?13/scale:7/scale)+'px Arial';ctx.textAlign='center';if(big)for(const [i,d] of districts.entries()){ctx.fillStyle=i<=phaseOf(a)?'#e3d4b5':'#788594';ctx.fillText(t(d.key)+(a.assembled.includes(i)?' ✓':i>phaseOf(a)?' · '+t('adv.locked'):''),d.center[0],d.center[1]-12);}}
 if(!indoor&&trail.length>1){ctx.strokeStyle='#84bfb077';ctx.lineWidth=1/scale;ctx.setLineDash([2/scale,3/scale]);ctx.beginPath();trail.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();ctx.setLineDash([]);}
 const nav=remainingRoute(pos,frameInfo.route);if(nav.length){ctx.strokeStyle=navigationColour(frameInfo.navigationTarget,!!mapPin);ctx.lineWidth=4/scale;ctx.beginPath();nav.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();}
 for(const action of actionsFor(a)){
  const item=action.id===frameInfo.navigationTarget?.id?frameInfo.navigationTarget:action;
  const selected=item.id===frameInfo.navigationTarget?.id,colour=navigationColour(item,mapPin?.actionId===item.id);
  ctx.save();ctx.translate(item.x,item.z);if(!big)ctx.rotate(-infoYaw());
  const size=(selected?9:7)/scale;ctx.fillStyle='#10202be6';ctx.strokeStyle=colour;ctx.lineWidth=(selected?2.5:1.5)/scale;
  ctx.beginPath();ctx.arc(0,0,size,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=colour;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`bold ${10/scale}px Arial`;ctx.fillText(item.kind==='gem'?'◆':item.id==='ladder'?'⇧':item.id==='lift'?'↕':'!',0,0);
  if(big){ctx.font=`${14/scale}px Arial`;ctx.textAlign='left';ctx.fillStyle='#fff';ctx.fillText(t(item.key),size+4/scale,0);}
  ctx.restore();
 }
 if(mapPin&&mapPin.location===a.location){
  ctx.save();ctx.translate(mapPin.x,mapPin.z);if(!big)ctx.rotate(-infoYaw());ctx.fillStyle='#65d5ff';ctx.strokeStyle='#e1faff';ctx.lineWidth=1/scale;
  const n=7/scale;ctx.beginPath();ctx.moveTo(0,n);ctx.lineTo(-n,-n*.6);ctx.lineTo(0,-n*1.5);ctx.lineTo(n,-n*.6);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();
 }
 ctx.save();ctx.translate(pos[0],pos[2]);ctx.rotate(-infoYaw());
 // Facing cone and a clear, fixed-size player chevron.
 ctx.fillStyle='#ffffff20';ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,36/scale,-Math.PI*.7,-Math.PI*.3);ctx.closePath();ctx.fill();
 ctx.fillStyle='#ffffff';ctx.strokeStyle='#13251b';ctx.lineWidth=1.5/scale;const n=7/scale;ctx.beginPath();ctx.moveTo(0,-n);ctx.lineTo(n*.65,n);ctx.lineTo(0,n*.55);ctx.lineTo(-n*.65,n);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();ctx.restore();
 // Compass labels follow the map rotation around its edge.
 if(!big){ctx.save();ctx.translate(w/2,h/2);ctx.rotate(infoYaw());ctx.font='bold 13px Arial';ctx.textAlign='center';ctx.textBaseline='middle';for(const [label,x,z] of [['N',0,-h/2+14],['E',w/2-14,0],['S',0,h/2-14],['W',-w/2+14,0]]){ctx.save();ctx.translate(x,z);ctx.rotate(-infoYaw());ctx.fillStyle=label==='N'?'#ffcf58':'#f1f3e9';ctx.fillText(label,0,0);ctx.restore();}ctx.restore();}
 else{ctx.strokeStyle='#d5e3cb22';ctx.lineWidth=1;ctx.font='11px Arial';ctx.fillStyle='#c9d9c2';ctx.textAlign='center';for(let i=1;i<6;i++){const x=i*w/6,y=i*h/6;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();ctx.fillText(String.fromCharCode(64+i),x-w/12,14);ctx.fillText(String(i),12,y-h/12);}ctx.fillText('N ↑',w-26,18);}

}
function bindMap(canvas){
 let drag=null,origin=null,moved=false;
 const redraw=()=>{drawMap(canvas,true);for(const b of document.querySelectorAll('[data-map-action]')){const chosen=b.dataset.mapAction===mapPin?.actionId;b.setAttribute('aria-pressed',String(chosen));const item=actionsFor(a).find(x=>x.id===b.dataset.mapAction);b.style.setProperty('--marker',navigationColour(item,chosen));}},zoom=d=>{mapView.zoom=Math.max(1,Math.min(4,mapView.zoom*d));redraw();};
 $('#zoomIn').onclick=()=>zoom(1.25);$('#zoomOut').onclick=()=>zoom(.8);$('#mapReset').onclick=()=>{mapView.zoom=2;const pos=world.position();mapView.x=pos[0];mapView.z=pos[2];redraw();};$('#clearMapPin').onclick=()=>{selectMapTarget(null);redraw();};
 for(const button of document.querySelectorAll('[data-map-action]'))button.onclick=()=>{const item=actionsFor(a).find(x=>x.id===button.dataset.mapAction);if(item){selectMapTarget({...item,actionId:item.id,location:a.location});mapView.x=item.x;mapView.z=item.z;mapView.zoom=3;redraw();}};
 canvas.addEventListener('pointerdown',e=>{origin=drag=[e.clientX,e.clientY];moved=false;canvas.setPointerCapture(e.pointerId);});
 canvas.addEventListener('pointermove',e=>{if(!drag||a.location==='lab')return;if(Math.hypot(e.clientX-origin[0],e.clientY-origin[1])<6&&!moved)return;moved=true;const scale=Math.min(canvas.width,canvas.height)/(650/mapView.zoom),rect=canvas.getBoundingClientRect();mapView.x-=(e.clientX-drag[0])*canvas.width/rect.width/scale;mapView.z-=(e.clientY-drag[1])*canvas.height/rect.height/scale;mapView.x=Math.max(-300,Math.min(300,mapView.x));mapView.z=Math.max(-300,Math.min(300,mapView.z));drag=[e.clientX,e.clientY];redraw();});
 canvas.addEventListener('pointerup',e=>{if(drag&&!moved){const rect=canvas.getBoundingClientRect(),indoor=a.location==='lab';const point=mapPoint((e.clientX-rect.left)*canvas.width/rect.width,(e.clientY-rect.top)*canvas.height/rect.height,canvas.width,canvas.height,indoor?45:650/mapView.zoom,indoor?{x:LAB_X,z:LAB_Z-5}:mapView);if(indoor||Math.abs(point.x)<=300&&Math.abs(point.z)<=300){const extent=indoor?45:650/mapView.zoom,hit=actionsFor(a).filter(item=>Math.hypot(item.x-point.x,item.z-point.z)<extent*20/Math.min(rect.width,rect.height)).sort((a,b)=>Math.hypot(a.x-point.x,a.z-point.z)-Math.hypot(b.x-point.x,b.z-point.z))[0];selectMapTarget({...point,...(hit||{}),actionId:hit?.id,location:a.location});}redraw();}drag=origin=null;});
 for(const name of ['pointercancel','lostpointercapture'])canvas.addEventListener(name,()=>drag=origin=null);
 canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?1.15:1/1.15);},{passive:false});
 canvas.addEventListener('keydown',e=>{const key=e.key;if(['+','=','-','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(key)){e.preventDefault();if(key==='+'||key==='=')zoom(1.25);else if(key==='-')zoom(.8);else{const d=25/mapView.zoom;mapView.x+=(key==='ArrowRight'?d:key==='ArrowLeft'?-d:0);mapView.z+=(key==='ArrowDown'?d:key==='ArrowUp'?-d:0);redraw();}}});
}
async function perform(id,accessible=false){if(busy)return;const item=actionsFor(a).find(x=>x.id===id);if(!item)return;if(!accessible&&frameInfo.nearest?.id!==id)return;
 if(id==='brief'){radio('adv.labBrief',12);music.effect('work');return;}
 if(id==='ladder'){releaseNeeded=true;work=0;workLatch=false;world.climb();music.effect('ladder_climb');return;}
 if(item.kind==='deliver'&&!frameInfo.driving&&!accessible){toast(t('adv.carNeed'));return;}
 busy=true;world.working?.(false);workLatch=false;releaseNeeded=true;work=0;try{
 if(id==='lift'){screen='elevator';$('#cinematic').classList.add('on');$('#cineTitle').textContent=t('adv.lab');$('#cineSubtitle').textContent=t(a.location==='city'?'cine.descent':'cine.ascent');world.pause(true);music.effect('elevator');conversation.cancel();radio(a.location==='city'?'conv.descent':'adv.surfaceArrival');event('elevator.start');if(!settings.text)await world.elevator(a.location==='city');a=act(a,id);if(settings.text)world.start(a.position);screen='city';world.pause(false);$('#cinematic').classList.remove('on');radio(a.location==='lab'?'adv.labArrival':'adv.surfaceArrival');event('elevator.complete');}
 else if(id==='assemble'){const index=a.stone;screen='cinematic';$('#cinematic').classList.add('on');$('#cineTitle').textContent=t('stone.'+index);$('#cineSubtitle').textContent=t('adv.assembly');world.pause(true);music.effect('handover',index);conversation.cancel();radio('conv.handover');event('assembly.start',{index});if(!settings.text)await world.assemble(index);a=act(a,id);screen='city';world.pause(false);$('#cinematic').classList.remove('on');radio(a.assembled.length===5?'radio.coreReady':'radio.assemble');$('#unlock').textContent=t(a.assembled.length===5?'adv.allStones':'adv.unlocked')+' · '+t(districts[Math.min(4,a.assembled.length)].key);$('#unlock').classList.add('visible');setTimeout(()=>$('#unlock').classList.remove('visible'),6000);music.effect('district_unlock');event('assembly.complete',{index});}
 else if(id==='activate'){a=act(a,id);screen='finale';world.pause(true);$('#cinematic').classList.add('on');$('#cineTitle').textContent=t('adv.finished');$('#cineSubtitle').textContent=t('adv.subtitle');const finale=settings.text?Promise.resolve():world.activate(a.ending.ending);music.effect('reactor');try{const res=await fetch('/api/verdict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decisions:a.rules.decisions,players:a.rules.scores.length,budget:a.rules.budget}),signal:AbortSignal.timeout(5000)});if(res.ok){a.ending=await res.json();serverChecked=true;}}catch{serverChecked=false;}if(!settings.text)await finale;$('#cinematic').classList.remove('on');event('ending.view',{ending:a.ending.ending});show('ending');conversation.cancel();conversation.play([{who:'asha',key:'conv.'+a.ending.ending+'Asha'},{who:'dadi',key:'conv.'+a.ending.ending+'Dadi',hold:6}]);}
 else{
  if(['housing1','housing2','water1','water2'].includes(id)&&!settings.text){
   event('ecology.animation.start',{id,kind:id.startsWith('water')?'planting':'survey'});
   music.effect(id.startsWith('water')?'water':'work');
   const completed=await world.ecologyAction(id);
   if(!completed)throw Error('Ecology action interrupted');
   event('ecology.animation.complete',{id});
  }
  a=act(a,id);event(item.kind==='gem'?'stone.collect':'task.complete',{id,phase:phaseOf(a)});if(id==='gem'||id==='override'){music.effect('stone_pickup',a.stone);radio('conv.stone');}else if(id==='night'){radio(a.night.ending==='critical'?'adv.fail':'adv.safe',12);music.effect(a.night.ending==='critical'?'error':'collect',4);}else if(id.startsWith('budget:')){toast(t(item.key)+(a.rules.budget.includes(id.slice(7))?' ✓':' ×'));music.effect('click');}else{music.effect('work');const key=id.startsWith('panel')&&id!=='panels'?'radio.panel':id.startsWith('water')?'radio.water':'radio.'+id;radio(key);}}
 revealActivity();persist();sync();if(settings.text)render();
 }catch(e){toast(t('adv.overbudget'));music.effect('error');event('action.rejected',{id,message:e.message});}finally{busy=false;}}
let lastHUDHeat=-1;
function tick(dt,info){frameInfo=info;document.body.dataset.cinematicStep=info.cinematic?Math.floor(info.cinematic.progress*10):'';document.body.dataset.playerX=info.position[0].toFixed(2);document.body.dataset.playerY=info.position[1].toFixed(2);document.body.dataset.playerZ=info.position[2].toFixed(2);document.body.dataset.modelLoaded=String(info.modelLoaded);document.body.dataset.driving=String(info.driving);audioBeat+=dt;if(audioBeat>.1){audioBeat=0;music.scene({...info,phase:phaseOf(a),heat:a.heat,stone:a.stone,active:['city','intro','cinematic','elevator','finale'].includes(screen)});}
 if(screen==='intro'){introTime+=dt;if(introTime>5&&introTime<5+dt*2)radio('adv.intro2');if(introTime>10&&introTime<10+dt*2)radio('adv.intro3');if(introTime>15){$('#cinematic').classList.remove('on','intro');show('city');}return;}
 if(screen!=='city')return;
 if(mapPin&&(mapPin.location!==a.location||mapPin.actionId&&!actionsFor(a).some(x=>x.id===mapPin.actionId)))selectMapTarget(null);
 const item=info.nearest,goal=info.navigationTarget||item,selected=!!mapPin,colour=navigationColour(goal,selected);
 $('#targetname').textContent=goal?t(goal.key||'nav.pin'):t('adv.ready');
 const length=routeLength(info.position,remainingRoute(info.position,info.route)),remaining=goal?Math.hypot(goal.x-info.position[0],goal.z-info.position[2]):0;
 $('#distance').textContent=goal?Math.round(length??remaining)+' '+t('adv.distance'):'';
 $('#bearing').textContent='➤';$('#bearing').style.color=colour;
 if(goal){const next=routeDirection(info.position,info.route,goal),angle=Math.atan2(Math.sin(Math.atan2(next[0]-info.position[0],-(next[1]-info.position[2]))+infoYaw()),Math.cos(Math.atan2(next[0]-info.position[0],-(next[1]-info.position[2]))+infoYaw()));$('#bearing').style.transform=`rotate(${angle-Math.PI/2}rad)`;$('#navturn').textContent=t(info.routeStatus==='blocked'?'nav.noRoute':remaining<2?(goal.kind==='pin'?'nav.pinArrived':'nav.arrived'):Math.abs(angle)<.35?'nav.forward':Math.cos(angle)<-.5?'nav.turnBack':Math.sin(angle)>0?'nav.turnRight':'nav.turnLeft');}
 const help=goal?.kind==='pin'?'nav.followPin':goal?.id==='lift'&&a.location==='lab'?'help.liftUp':goal?.id.startsWith('budget:')?'help.budget':'help.'+goal?.id;$('#taskhelp').textContent=t(help)===help?t('help.default'):t(help);
 compass.update(compassHeading(-infoYaw()),goal?worldBearing(info.position,goal):null,remaining,colour);$('#compassWaypoint').classList.toggle('custom-pin',selected);
 trafficSoundTime+=dt;if(trafficSoundTime>2.5&&a.location==='city'){trafficSoundTime=0;const near=(info.traffic||[]).find(v=>Math.hypot(v.x-info.position[0],v.z-info.position[2])<8);if(near)music.effect('traffic_warning');else if((info.traffic||[]).some(v=>Math.hypot(v.x-info.position[0],v.z-info.position[2])<18))music.effect('traffic_pass',info.traffic[0].direction);}
 const inRange=item&&item.distance<(info.driving?3:2.2);$('#prompt').classList.toggle('visible',!!inRange);$('#interactlabel').textContent=inRange?t('adv.hold')+' '+(item.kind==='scan'?'Q / E':'E')+' · '+t(item.key):'';
 const held=workLatch||world.keys.has('e')||world.keys.has('E')||(item?.kind==='scan'&&world.keys.has('q'));world.working?.(held&&inRange&&!busy);if(!inRange){workLatch=false;work=0;}if(inRange&&held&&!releaseNeeded&&!busy){if(workId!==item.id){workId=item.id;work=0;}work+=dt/item.duration;const band=Math.floor(work*5);if(band!==progressBand){progressBand=band;music.effect('task_progress',Math.min(1,work));}$('#workfill').style.width=Math.min(100,work*100)+'%';if(work>=1)perform(item.id);}else if(!held){work=0;workId='';progressBand=-1;releaseNeeded=false;$('#workfill').style.width='0%';}
 // Heat is immediate survival pressure; shade and the lab are safe cooling spaces.
 const cool=a.location==='lab'||Math.hypot(info.position[0]-lift[0],info.position[2]-lift[1])<15||Math.hypot(info.position[0]-112,info.position[2]+109)<35||Math.hypot(info.position[0]+53,info.position[2]-30)<12;if(heatCooldown>0){heatCooldown-=dt;a.heat=Math.max(0,a.heat-dt*10);}else a.heat=Math.max(0,Math.min(100,a.heat+dt*(cool?-5:info.driving?.12:world.keys.has('Shift')?1.2:.2)));document.body.classList.toggle('heat-active',!reduced&&a.heat>50);$('#heat-shimmer').style.opacity=reduced?0:Math.max(0,(a.heat-50)/150);$('#damage').style.opacity=Math.max(0,(a.heat-65)/60);if(a.heat>=100){a.location='city';world.start(spawn);world.pause(false);a.heat=45;heatCooldown=8;work=0;toast(t('adv.exhausted'));music.effect('error');event('player.heat_exhaustion');persist();}
 taskBeat+=dt;if(taskBeat>.2){taskBeat=0;if(a.location==='city'){const x=info.position[0],z=info.position[2];for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)explored.add((Math.floor(x/20)+dx)+','+(Math.floor(z/20)+dz));if(!trail.length||Math.hypot(x-trail.at(-1)[0],z-trail.at(-1)[1])>2){trail.push([x,z]);if(trail.length>150)trail.shift();}}drawMap($('#minimap'));if(Math.round(a.heat)!==lastHUDHeat){lastHUDHeat=Math.round(a.heat);renderHUD();}semantic.textContent=JSON.stringify(snapshot());}if(info.driving)$('#distance').textContent+=` / ${Math.round(info.speed)} ${t('adv.speed')}`;
}
// The menu and accessibility mode never allocate WebGL, models or city geometry.
// Start the 3D renderer only after the player chooses to enter the world.
const textWorld={keys:new Set(),hooks(){},working(){},update(){},pause(){},stop(){this.keys.clear();},
 start(pos=spawn){a.position=[...pos];this.keys.clear();},position:()=>a.position,nearest:()=>null,
 text(){},quality(){},jump(){},camera(){},scan(){},climb(){},moveFor(){},vehicle:()=>false,
 elevator:()=>Promise.resolve(),assemble:()=>Promise.resolve(),activate:()=>Promise.resolve()};
world=textWorld;
function prepareWorld(){
 if(world!==textWorld||settings.text)return;
 try{
  world=createWorld($('#world'),fps=>$('#fps').textContent=settings.text?t('adv.textmode'):fps+' FPS',{quality:settings.quality});
  world.hooks(tick,(name,props)=>{
   if(name==='footstep')music.effect(world.keys.has('Shift')?'runstep':'footstep');
   else if(['jump','land','ladder_climb'].includes(name))music.effect(name);
   else if(name==='brake')music.effect('brake_screech');
   else if(name==='scanner')music.effect('scanner');
   else if(name==='vehicle.bump')music.effect('error');
   else if(name==='traffic.hit'){a.heat=Math.min(100,a.heat+18);toast(t('adv.traffic'));music.effect('error');event('player.traffic_hit');}
   else if(name==='district.locked'){toast(t('adv.lockedHelp'));music.effect('error');}
   else if(name==='cinematic.stage'){if(props.id!==cineStage){cineStage=props.id;$('#cineSubtitle').textContent=t('cine.'+props.id);if(props.id==='activation')music.effect('assemble',a.stone);if(['doorsClose','doorsOpen','surfaceOpen'].includes(props.id))music.effect('door');event('cinematic.stage',{id:props.id});}}
   else if(name==='models.ready')event(name);
  });
  world.quality(settings.quality);world.text(false);
 }catch(e){settings.text=true;world=textWorld;event('renderer.unavailable',{message:e.message});}
}
async function begin(){if(!settings.text)prepareWorld();running=true;world.start(a.tasks.length||a.assembled.length?a.position:spawn,a.vehicle);if(!music.enabled()){try{await music.toggle();$('#sound').textContent='♪ ON';}catch{}}if(a.ending){show('ending');}else if(a.tasks.length||a.assembled.length){show('city');radio(a.location==='lab'?(a.stone>=0?'adv.labArrival':'adv.exitLab'):a.stone>=0?'adv.return':'adv.intro3');}else{show(settings.text?'city':'intro');introTime=0;radio('adv.intro1');if(!settings.text){$('#cinematic').classList.add('on','intro');$('#cineTitle').textContent=t('adv.subtitle');$('#cineSubtitle').textContent=t('adv.skip');}}event('adventure.start');persist();}
document.addEventListener('click',e=>{if(e.target.closest('button'))music.effect('menu_click');});document.addEventListener('pointerover',e=>{if(e.target.matches('button'))music.effect('menu_hover');});
ui.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const id=b.dataset.action;if(id==='begin')begin();else if(id==='city')show('city');else if(id==='return')show(previous);else if(id==='guide'){previous=screen;show('guide');}else if(id==='restart'){conversation.cancel();mapPin=null;explored.clear();trail.length=0;a=freshAdventure();running=false;world.start(a.position);world.stop();persist();$('#cinematic').classList.remove('on','intro');show('home');}else if(id==='retry'){conversation.cancel();a.ending=null;if(a.assembled.length===5)a.assembled.pop();a.stone=-1;a.inventory='';a.night=null;a.location='city';world.start([-121,0,191]);running=true;show('city');persist();}else if(id.startsWith('accessible:'))perform(id.slice(11),true);});
$('#settings').addEventListener('click',()=>{previous=screen;show('settings');});$('#pauseBtn').addEventListener('click',()=>{persist();show('pause');});$('#mapBtn').addEventListener('click',()=>show(screen==='map'?'city':'map'));$('#minimapToggle').addEventListener('click',()=>show(screen==='map'?'city':'map'));$('#questToggle').addEventListener('click',()=>{clearTimeout(questTimer);questPinned=!$('#missionbox').classList.contains('expanded');activityBoard(questPinned);});$('#locale').addEventListener('change',e=>{settings.locale=e.target.value;setLocale(settings.locale);persist();render();});$('#sound').addEventListener('click',async()=>{try{$('#sound').textContent=await music.toggle()?'♪ ON':'♪ OFF';}catch{}});
function vehicle(){if(world.vehicle()){music.effect('vehicle');event('vehicle.toggle');}else toast(t('adv.carNeed'));}
addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea,[contenteditable="true"]'))return;const key=gameplayKey(e),keyScreen=screen;if(screen==='intro'&&key==='Enter'){conversation.cancel();$('#cinematic').classList.remove('on','intro');show('city');return;}if(screen==='city'){if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Shift','e','E','q',' '].includes(key)){e.preventDefault();world.keys.add(key);}if(!e.repeat){if(key.toLowerCase()==='h'&&frameInfo.driving)music.effect('car_horn');if(key==='Enter'&&conversation.isActive()){e.preventDefault();conversation.skip();}if(key.toLowerCase()==='f')vehicle();if(key.toLowerCase()==='c')world.camera();if(key.toLowerCase()==='q')world.scan();if(key===' ')world.jump();if(key.toLowerCase()==='m')show('map');}}
 if(keyScreen==='map'&&key.toLowerCase()==='m'){e.preventDefault();show('city');}if(screen==='ending'&&key==='Enter'&&conversation.isActive()){e.preventDefault();conversation.skip();}if(key==='Escape'){e.preventDefault();if(screen==='city'){persist();show('pause');}else if(['pause','map','guide','settings'].includes(screen))show(running?'city':'home');}if(key==='Tab'&&$('.panel')){const items=[...$('.panel').querySelectorAll('button,select,input')];if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('.panel'))){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
addEventListener('keyup',e=>{const key=gameplayKey(e);world.keys.delete(key);if(['e','E','q'].includes(key))releaseNeeded=false;});addEventListener('blur',()=>world.keys.clear());document.addEventListener('visibilitychange',()=>{world.keys.clear();if(document.hidden){persist();music.suspend();}else music.resume();});addEventListener('pagehide',persist);
for(const b of document.querySelectorAll('[data-move]')){const key={up:'w',down:'s',left:'a',right:'d'}[b.dataset.move];b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);b.dataset.down=performance.now();b.dataset.held='1';world.keys.add(key);});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>{if(b.dataset.held!=='1')return;b.dataset.held='0';world.keys.delete(key);if(name==='pointerup'&&performance.now()-Number(b.dataset.down)<180)world.moveFor(key,.45);});}
$('#interactTouch').addEventListener('click',()=>{workLatch=!workLatch;releaseNeeded=false;});$('#interactTouch').addEventListener('pointerdown',e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);world.keys.add('e');releaseNeeded=false;});for(const name of ['pointerup','pointercancel','lostpointercapture'])$('#interactTouch').addEventListener(name,()=>{world.keys.delete('e');releaseNeeded=false;});$('#cameraTouch').onclick=()=>world.camera();$('#vehicleTouch').onclick=vehicle;$('#scanTouch').onclick=()=>world.scan();$('#jumpTouch').onclick=()=>world.jump();
let dialogueLast=performance.now();function dialogueFrame(now){const dt=Math.min(.1,(now-dialogueLast)/1000);dialogueLast=now;if(!document.hidden&&['city','intro','cinematic','elevator','finale','ending'].includes(screen))conversation.tick(dt);requestAnimationFrame(dialogueFrame);}requestAnimationFrame(dialogueFrame);
setInterval(()=>{if(running&&screen==='city')persist();},5000);Object.defineProperty(window,'mission2050',{value:Object.freeze({snapshot:()=>structuredClone(snapshot()),navigation:()=>structuredClone(world.navigation?.()||{})})});render();event('app.ready');
