import {createWorld} from './world.js';
import {audio} from './audio.js';
import {fresh,decide,assess,restore,budgetTotal,costs,choices} from './rules.js';
import {t,setLocale,currentLocale} from './locale.js';
const $=s=>document.querySelector(s),ui=$('#ui'),hud=$('#hud'),music=audio(),stages=['energy','solar','land','river','transport'],days=[4,9,15,21,29],glyphs=['ϟ','☀','♧','≈','↔'];
let saveAvailable=true,settings={quality:'low',text:false,volume:.3,locale:'en'},state=fresh(),running=false,screen='home',previous='city',inspected=new Set(),result=null,resultId='',report=null,serverChecked=false,busy=false,lastFocus=null,toastTimer;
try{settings={...settings,...JSON.parse(localStorage.getItem('m2050.settings')||'{}')};const saved=restore(localStorage.getItem('m2050.save'));if(saved)state=saved;}catch{saveAvailable=false;}
setLocale(settings.locale);$('#locale').value=currentLocale();music.volume(settings.volume);
const semantic=document.createElement('output');semantic.id='game-state';semantic.hidden=true;document.body.append(semantic);const events=[];function event(name,props={}){events.push({name,...props,locale:currentLocale(),at:Math.round(performance.now())});if(events.length>250)events.shift();window.dispatchEvent(new CustomEvent('mission2050:event',{detail:events.at(-1)}));}
let world;try{world=createWorld($('#world'),fps=>{$('#fps').textContent=settings.text?t('settings.textshort'):fps+' FPS';if(fps<25&&running)event('performance.low_fps',{fps});});world.quality(settings.quality);world.text(settings.text);world.update(state);}catch(e){settings.text=true;event('renderer.unavailable');toast('3D unavailable. Text mode is ready.');world={keys:new Set(),stop(){},start(){},pause(){},position:()=>[0,9],near:()=>true,update(){},quality(){},text(){}};}
document.body.classList.toggle('textmode',settings.text);
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}function tr(k){return esc(t(k));}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2400);}
function save(){state.position=world.position();try{localStorage.setItem('m2050.save',JSON.stringify(state));saveAvailable=true;}catch{saveAvailable=false;event('save.failure');}}
function saveSettings(){try{localStorage.setItem('m2050.settings',JSON.stringify(settings));}catch{}}
function button(label,action,cls='',disabled=false){return `<button data-action="${action}" class="${cls}" ${disabled?'disabled':''}>${tr(label)}</button>`;}
function modal(content){return `<div class="modalwrap"><section class="panel" role="dialog" aria-modal="true" aria-labelledby="paneltitle" tabindex="-1">${content}</section></div>`;}
function title(key){return `<h2 id="paneltitle">${tr(key)}</h2>`;}function detail(){return `<p class="caption">${tr('ui.detail')}</p>`;}
function show(next){if(screen==='city')lastFocus=document.activeElement;screen=next;world.pause(next!=='city');render();if(next!=='city'&&next!=='home')queueMicrotask(()=>$('.panel')?.focus());else if(next==='city')lastFocus?.focus?.();}
function renderHUD(){if(settings.text)$('#fps').textContent=t('settings.textshort');document.body.dataset.screen=screen;document.body.dataset.stage=String(state.stage);semantic.textContent=JSON.stringify({version:1,screen,state,report,locale:currentLocale()});const k=stages[state.stage]||'transport';$('#day').textContent=t('ui.day')+' '+days[Math.min(state.stage,4)]+' / 30';$('#objective').textContent=t(k+'.goal');$('#hint').textContent=t(k+'.hint');$('#missionBtn').textContent=t('ui.mission');$('#controls').textContent=t('ui.controls');$('#ledgerBtn').textContent=t('ui.ledger');$('#pauseBtn').textContent=t('ui.pause');$('#meters').innerHTML=[['carbon',state.carbon],['energy',state.energy],['eco',state.ecosystem]].map(([k,v])=>`<div class="meter"><label>${tr('ui.'+k)} <b>${v}</b></label><div class="track"><div class="fill" style="width:${v}%"></div></div></div>`).join('');$('#corebar').innerHTML=Array.from({length:5},(_,i)=>`<div class="core ${i<state.stage||(i===4&&report?.ending!=='critical'&&report)?'active':''}" title="${tr('ui.core')} ${i+1}"><span>${i+1}</span></div>`).join('');}
function render(){hud.hidden=!running;renderHUD();let html='';
 if(screen==='home'){html=`<section class="hero"><div class="eyebrow">${tr('hero.eyebrow')}</div><h1>MISSION<span>2050</span></h1><div class="subtitle">${tr('hero.sub')}</div><p>${tr('hero.desc')}</p><div class="actions">${button(state.decisions.length?'hero.continue':'hero.start',state.decisions.length?'continue':'setup','primary')}${button('hero.how','guide')}</div><div class="tagrow"><span>01 / ${tr('hero.tag1')}</span><span>02 / ${tr('hero.tag2')}</span><span>03 / ${tr('hero.tag3')}</span></div></section><div class="herofooter">${tr('hero.footer')}</div><div class="coordinates">${tr('hero.location').replace('\n','<br>')}</div>`;}
 if(screen==='setup'){html=modal(`${title('setup.title')}<p>${tr('setup.desc')}</p><div class="actions">${[1,2,3,4].map(n=>`<button data-action="players:${n}" class="${state.scores.length===n?'primary':''}">${n===1?tr('setup.solo'):n+' '+tr('setup.team')}</button>`).join('')}</div><div class="actions">${button('setup.start','intro','primary')}${button('ui.close','home')}</div>`);}
 if(screen==='intro'){html=modal(`<div class="speaker">${tr('intro.speaker')}</div>${title('intro.title')}<p class="dialogue">${tr('intro.body')}</p><p>${tr('intro.twist')}</p><p>${tr('intro.controls')}</p><div class="actions">${button('ui.enter','begin','primary')}${button('ui.skip','begin')}</div>${detail()}`);}
 if(screen==='mission'){const k=stages[state.stage];const total=budgetTotal(state.budget);html=modal(`<div class="eyebrow">${tr('ui.day')} ${days[state.stage]} / 30 · ${tr('ui.player')} ${state.decisions.length%state.scores.length+1}</div>${title(k+'.title')}<div class="speaker">${tr(k+'.speaker')}</div><p class="dialogue">${tr(k+'.body')}</p><div class="split"><div><p class="caption">${tr('ui.inspect')}</p>${[1,2].map(i=>`<button class="evidence ${inspected.has(i)?'selected':''}" data-action="evidence:${i}" aria-pressed="${inspected.has(i)}"><strong>${inspected.has(i)?'✓ ':''}${tr(k+'.e'+i)}</strong><small>${inspected.has(i)?tr(k+'.d'+i):tr('ui.inspect')}</small></button>`).join('')}${k==='solar'?`<div class="roofs"><div class="roof">6 h · 10 × 6 = 60</div><div class="roof shaded">3 h · 10 × 3 = 30</div><div class="roof">4.5 h · 10 × 4.5 = 45</div></div>`:''}</div><div>${k==='transport'?`<div class="budgethead"><span>${tr('ui.budget')}</span><b>${total} / 100</b></div>`:''}<div class="choices">${(k==='transport'?Object.keys(costs):choices[k].map(c=>c.id)).map((id,i)=>`<button class="choice ${state.budget.includes(id)?'selected':''}" data-action="${k==='transport'?'budget':'choose'}:${id}" ${inspected.size<2||k==='transport'&&!state.budget.includes(id)&&total+costs[id]>100?'disabled':''} ${k==='transport'?`aria-pressed="${state.budget.includes(id)}"`:''}><span class="glyph">${k==='transport'?['▰','↗','ϟ','◎','═','◈'][i]:glyphs[state.stage]}</span><span><strong>${tr(k+'.c'+i)}</strong><small>${tr(k+'.cd'+i)}</small></span>${k==='transport'?`<span class="cost">${costs[id]}</span>`:''}</button>`).join('')}</div></div></div><div class="actions">${k==='transport'?button('ui.test','test','primary',inspected.size<2||!state.budget.length):''}${button('ui.back','city')}</div>${detail()}`);}
 if(screen==='result'){const k=stages[state.stage-1],idx=choices[k].findIndex(c=>c.id===resultId);html=modal(`<div class="eyebrow">${tr('ui.core')} ${state.stage} / 5 · ${tr('ui.result')}</div>${title(k+'.title')}<p class="dialogue">${tr(k+'.r'+idx)}</p><div class="statgrid"><div class="stat"><b>${state.carbon}</b>${tr('ui.carbon')}</div><div class="stat"><b>${state.energy}</b>${tr('ui.energy')}</div><div class="stat"><b>${state.ecosystem}</b>${tr('ui.eco')}</div></div><p class="caption">${tr(saveAvailable?'ui.saved':'ui.unsaved')}</p><div class="actions">${button('ui.next','city','primary')}${button('ui.ledger','ledger')}</div>`);}
 if(screen==='night'){const r=result;html=modal(`<div class="eyebrow">ECO-CORE / ${tr('ui.day')} 29</div>${title(r.checks.clinic?'transport.title':'night.title')}<p class="dialogue">${tr(r.checks.clinic?'night.safe':'night.body')}</p><div class="statgrid"><div class="stat"><b>${r.reserve} / 10</b>${tr('night.clinic')}</div><div class="stat"><b>${r.carbon}</b>${tr('ui.carbon')}</div><div class="stat"><b>${r.total} / 100</b>${tr('ui.budget')}</div></div><div>${Object.entries(r.checks).map(([k,v])=>`<div class="check ${v?'pass':'fail'}">${v?'✓':'×'} ${tr('night.'+(k==='ecosystem'?'eco':k))}</div>`).join('')}</div><div class="actions">${button('ui.amend','amend','primary')}${button(r.ending==='critical'?'night.commit':'ui.activate','commit','',busy)}</div>${detail()}`);}
 if(screen==='ending'){html=modal(`<div class="eyebrow">${tr('ui.day')} 30 / ${report.ending==='critical'?'4':'5'} ${tr('ui.core')}</div><h1 id="paneltitle" class="endtitle">${tr('ending.'+report.ending)}</h1><p class="dialogue">${tr('ending.'+report.ending+'body')}</p><div class="eyebrow">${tr('ending.refrain')}</div><div class="statgrid"><div class="stat"><b>${report.carbon}</b>${tr('ui.carbon')}</div><div class="stat"><b>${report.energy}</b>${tr('ui.energy')}</div><div class="stat"><b>${report.ecosystem}</b>${tr('ui.eco')}</div></div><p>${tr('ending.guardian')}: ${state.scores.map((s,i)=>s===Math.max(...state.scores)?`${tr('ui.player')} ${i+1}`:null).filter(Boolean).join(' / ')}<br>${state.scores.map((s,i)=>`${tr('ui.player')} ${i+1}: ${s+(report.ending==='green'?40:report.ending==='survival'?10:-20)}`).join(' · ')}</p><p class="caption">${tr(serverChecked?'ui.server':'ui.local')}</p><div class="actions">${button('ending.revise','amend','primary')}${button('ui.ledger','ledger')}${button('ending.share','share')}${button('ui.restart','restart')}</div>${detail()}`);}
 if(screen==='ledger'){html=modal(`${title('ledger.title')}<p class="caption">${tr('ledger.note')}</p>${state.decisions.length?state.decisions.map(d=>{const i=choices[d.stage].findIndex(c=>c.id===d.id);return `<div class="ledgerrow"><strong>${tr(d.stage+'.title')}</strong><p>${tr(d.stage+'.c'+i)}</p><p>${tr('ledger.owner')}: ${tr('owner.'+d.stage)}</p><p>${tr('ledger.review')}: ${tr('review.'+d.stage)}</p></div>`;}).join(''):`<p>${tr('ledger.empty')}</p>`}<div class="actions">${button('ui.close','return','primary')}</div>`);}
 if(screen==='guide'){html=modal(`${title('guide.title')}<p>${tr('guide.body')}</p><p>${tr('guide.controls')}</p><p>${tr('guide.win')}</p><p class="caption">${tr('guide.credits')}</p><div class="actions">${button('ui.close','return','primary')}</div>${detail()}`);}
 if(screen==='settings'){html=modal(`${title('settings.title')}<label class="settingsrow">${tr('settings.quality')}<select id="quality"><option value="high" ${settings.quality==='high'?'selected':''}>${tr('settings.high')}</option><option value="low" ${settings.quality==='low'?'selected':''}>${tr('settings.low')}</option></select></label><label class="settingsrow">${tr('settings.text')}<input id="textmode" type="checkbox" ${settings.text?'checked':''}></label><label class="settingsrow">${tr('settings.volume')}<input id="volume" aria-label="${tr('settings.volume')}" type="range" min="0" max="1" step=".05" value="${settings.volume}"></label><p>${tr('settings.motion')}</p><div class="actions">${button('ui.close','return','primary')}</div>`);}
 if(screen==='pause'){html=modal(`${title('ui.pause')}<p>${tr('ui.saved')}</p><div class="actions">${button('ui.resume','city','primary')}${button('hero.how','guide')}${button('ui.restart','restart')}</div>`);}
 ui.innerHTML=html;event('menu.view',{screen});
 $('#quality')?.addEventListener('change',e=>{settings.quality=e.target.value;world.quality(settings.quality);saveSettings();event('settings.quality',{quality:settings.quality});});$('#textmode')?.addEventListener('change',e=>{settings.text=e.target.checked;document.body.classList.toggle('textmode',settings.text);world.text(settings.text);saveSettings();});$('#volume')?.addEventListener('input',e=>{settings.volume=Number(e.target.value);music.volume(settings.volume);saveSettings();});
}
function openMission(){if(!running)return;inspected=new Set();show('mission');event('mission.open',{stage:stages[state.stage]});}
ui.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const [action,id]=b.dataset.action.split(':');music.effect('click');
 if(action==='setup')show('setup');
 else if(action==='players'){state=fresh(Number(id));render();}
 else if(action==='intro'){state=fresh(state.scores.length);event('mission.start',{players:state.scores.length});show('intro');}
 else if(action==='begin'||action==='continue'){running=true;world.start(action==='continue'?state.position:[0,15]);show('city');save();event('onboarding.city_enter');}
 else if(action==='evidence'){inspected.add(Number(id));render();event('evidence.inspect',{stage:stages[state.stage],id:Number(id)});}
 else if(action==='choose'){if(inspected.size<2)return;resultId=id;state=decide(state,stages[state.stage],id);world.update(state);save();music.effect('core');event('decision.commit',{stage:stages[state.stage-1],id});show('result');}
 else if(action==='budget'){if(inspected.size<2)return;const ids=state.budget.includes(id)?state.budget.filter(x=>x!==id):[...state.budget,id];if(budgetTotal(ids)>100)return;state.budget=ids;save();render();event('budget.change',{id,total:budgetTotal(ids)});}
 else if(action==='test'){result=assess(state,state.budget);show('night');music.effect(result.ending==='critical'?'error':'core');event('night_test.complete',{ending:result.ending,clinic:result.checks.clinic});}
 else if(action==='amend'){inspected=new Set([1,2]);report=null;show('mission');event('plan.amend');}
 else if(action==='commit'){if(busy)return;busy=true;render();report=assess(state,state.budget);serverChecked=false;try{const response=await fetch('/api/verdict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decisions:state.decisions,budget:state.budget,players:state.scores.length}),signal:AbortSignal.timeout(5000)});if(response.ok){const r=await response.json();if(['green','survival','critical'].includes(r.ending)){report=r;serverChecked=true;}}}catch{event('server.unavailable');}busy=false;save();world.update({...state,carbon:report.carbon,energy:report.energy,ecosystem:report.ecosystem});show('ending');music.effect(report.ending==='critical'?'error':'core');event('ending.view',{ending:report.ending});}
 else if(action==='city'){show('city');}
 else if(action==='home'){running=false;world.stop();show('home');}
 else if(action==='restart'){save();running=false;world.stop();state=fresh(state.scores.length);report=null;world.update(state);save();show('setup');event('mission.restart');}
 else if(['ledger','guide'].includes(action)){previous=screen;show(action);}
 else if(action==='return')show(previous);
 else if(action==='share'){const text=`MISSION 2050 — ${t('ending.'+report.ending)}\nCarbon ${report.carbon} · Clean supply ${report.energy} · Ecosystem ${report.ecosystem}\nClinic reserve ${report.reserve} · Worker support ${report.workers}\n${t('ending.refrain')}\nFictional learning simulation.`;try{await navigator.clipboard.writeText(text);toast(t('ending.copied'));}catch{toast(text);}}
});
$('#missionBtn').addEventListener('click',openMission);$('#interactTouch').addEventListener('click',()=>{if(world.near(state.stage)||settings.text)openMission();else toast(t(stages[state.stage]+'.hint'));});$('#prompt').addEventListener('click',openMission);$('#ledgerBtn').addEventListener('click',()=>{previous=screen;show('ledger');});$('#pauseBtn').addEventListener('click',()=>{save();show('pause');});$('#settings').addEventListener('click',()=>{previous=screen;show('settings');});$('#sound').addEventListener('click',async()=>{try{const on=await music.toggle();$('#sound').textContent=on?'♪ ON':'♪ OFF';event('audio.toggle',{on});}catch{toast('Audio unavailable');}});$('#locale').addEventListener('change',e=>{settings.locale=e.target.value;setLocale(settings.locale);saveSettings();render();});
addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(screen==='city'&&['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Shift'].includes(e.key)){e.preventDefault();world.keys.add(e.key);}if(screen==='city'&&e.key.toLowerCase()==='e'){if(world.near(state.stage)||settings.text)openMission();else toast(t(stages[state.stage]+'.hint'));}if(screen==='city'&&e.key.toLowerCase()==='m'){previous=screen;show('ledger');}if(e.key==='Escape'){e.preventDefault();if(screen==='city'){save();show('pause');}else if(['mission','pause','result','night'].includes(screen))show('city');else if(['ledger','guide','settings'].includes(screen))show(previous);}if(e.key==='Tab'&&$('.panel')){const elements=[...$('.panel').querySelectorAll('button:not(:disabled),select,input')];if(!elements.length)return;const first=elements[0],last=elements.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('.panel'))){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
addEventListener('keyup',e=>world.keys.delete(e.key));addEventListener('blur',()=>world.keys.clear());document.addEventListener('visibilitychange',()=>{world.keys.clear();if(document.hidden){if(running)save();music.suspend();}else music.resume();});addEventListener('pagehide',()=>{if(running)save();});
for(const b of document.querySelectorAll('[data-move]')){const key={up:'w',left:'a',down:'s',right:'d'}[b.dataset.move];b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);world.keys.add(key);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>world.keys.delete(key));}
setInterval(()=>{document.body.dataset.playerX=world.position()[0].toFixed(2);document.body.dataset.playerZ=world.position()[1].toFixed(2);if(screen!=='city'){$('#prompt').textContent='';return;}$('#prompt').textContent=world.near(state.stage)||settings.text?t('ui.interact'):'';},150);
setInterval(()=>{if(running&&screen==='city')save();},5000);
// Read-only semantic snapshot; real input and DOM buttons are the automation actions.
Object.defineProperty(window,'mission2050',{value:Object.freeze({snapshot:()=>structuredClone({version:1,screen,state,report,locale:currentLocale(),events}),actions:Object.freeze(['mission.open','evidence.inspect','decision.commit','budget.change','night_test.complete','plan.amend','ending.view'])}),writable:false});
event('app.ready');render();
